[package]
name = "section3"
version = "0.1.0"
authors = ["Terry Lowery <tl@lowerytech.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
